#include"stm32f767xx.h"

uint16_t buf[7];

void EXTI0_IRQHandler()
{
	EXTI->PR |= EXTI_PR_PR0;
}

void EXTI1_IRQHandler()
{
	EXTI->PR |= EXTI_PR_PR1;
}

void EXTI2_IRQHandler()
{
	EXTI->PR |= EXTI_PR_PR2;
}

void EXTI3_IRQHandler()
{
	EXTI->PR |= EXTI_PR_PR3;
}

void EXTI4_IRQHandler()
{
	EXTI->PR |= EXTI_PR_PR4;
}

void EXTI9_5_IRQHandler()
{
	EXTI->PR |= EXTI_PR_PR5;
}

void EXTI15_10_IRQHandler()
{
	EXTI->PR |= EXTI_PR_PR10;
}

void __init_all()
{
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN | RCC_AHB1ENR_GPIOBEN | RCC_AHB1ENR_GPIOCEN;
	RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN | RCC_APB2ENR_USART1EN;

	SYSCFG->EXTICR[0] |= SYSCFG_EXTICR1_EXTI0_PB | SYSCFG_EXTICR1_EXTI1_PB | SYSCFG_EXTICR1_EXTI2_PB | SYSCFG_EXTICR1_EXTI3_PB;
	SYSCFG->EXTICR[1] |= SYSCFG_EXTICR2_EXTI4_PB | SYSCFG_EXTICR2_EXTI5_PB;
	SYSCFG->EXTICR[2] |= SYSCFG_EXTICR3_EXTI8_PB | SYSCFG_EXTICR3_EXTI9_PB | SYSCFG_EXTICR3_EXTI10_PB | SYSCFG_EXTICR3_EXTI11_PB;
	EXTI->IMR |= EXTI_IMR_MR1 | EXTI_IMR_MR2 | EXTI_IMR_MR3 | EXTI_IMR_MR4 | EXTI_IMR_MR5 | EXTI_IMR_MR8 | EXTI_IMR_MR9 | EXTI_IMR_MR10 | EXTI_IMR_MR11;
	EXTI->RTSR |= EXTI_RTSR_TR1 | EXTI_RTSR_TR2 | EXTI_RTSR_TR3 | EXTI_RTSR_TR4 | EXTI_RTSR_TR5 | EXTI_RTSR_TR8 | EXTI_RTSR_TR9 | EXTI_RTSR_TR10 | EXTI_RTSR_TR11;
	NVIC_EnableIRQ(EXTI0_IRQn);
	NVIC_EnableIRQ(EXTI1_IRQn);
	NVIC_EnableIRQ(EXTI2_IRQn);
	NVIC_EnableIRQ(EXTI3_IRQn);
	NVIC_EnableIRQ(EXTI4_IRQn);
	NVIC_EnableIRQ(EXTI4_IRQn);
	NVIC_EnableIRQ(EXTI9_5_IRQn);
	NVIC_EnableIRQ(EXTI15_10_IRQn);
	__enable_irq();

	GPIOA->MODER |= GPIO_MODER_MODER8_0 | GPIO_MODER_MODER13_0 | GPIO_MODER_MODER14_0 | GPIO_MODER_MODER15_0;
	GPIOB->MODER |= GPIO_MODER_MODER12_0 | GPIO_MODER_MODER13_0 | GPIO_MODER_MODER14_0 | GPIO_MODER_MODER15_0;

	GPIOA->MODER |= GPIO_MODER_MODER0 | GPIO_MODER_MODER1 | GPIO_MODER_MODER6 | GPIO_MODER_MODER7;
	GPIOC->MODER |= GPIO_MODER_MODER0 | GPIO_MODER_MODER1 | GPIO_MODER_MODER2;
	ADC1->SQR1 |= ADC_SQR1_L_1 | ADC_SQR1_L_2;
	ADC1->SQR3 |= ADC_SQR3_SQ2_0 | ADC_SQR3_SQ3_2 | ADC_SQR3_SQ3_1 | ADC_SQR3_SQ4_2 | ADC_SQR3_SQ4_1 | ADC_SQR3_SQ4_0 | ADC_SQR3_SQ5_3 | ADC_SQR3_SQ5_1 | ADC_SQR3_SQ6_3 | ADC_SQR3_SQ6_1 | ADC_SQR3_SQ6_0;
	ADC1->SQR2 |= ADC_SQR2_SQ7_3 | ADC_SQR2_SQ7_2;
	ADC1->CR1 |= ADC_CR1_SCAN;
	ADC1->CR2 |= ADC_CR2_DMA | ADC_CR2_DDS | ADC_CR2_CONT | ADC_CR2_ADON;

	DMA2_Stream0->CR &= ~DMA_SxCR_EN;
	DMA2_Stream0->CR  |= DMA_SxCR_MSIZE_0 | DMA_SxCR_PSIZE_0 | DMA_SxCR_MINC;
	DMA2_Stream0->PAR = (uint32_t)&ADC1->DR;
	DMA2_Stream0->M0AR = (uint32_t)&buf;
	DMA2_Stream0->NDTR = 7;
   	DMA2_Stream0->CR |= DMA_SxCR_EN;

	GPIOA->MODER |= GPIO_MODER_MODER2_1 | GPIO_MODER_MODER3_1;
	GPIOA->AFR[0] |= GPIO_AFRL_AFRL2_2 | GPIO_AFRL_AFRL2_1 | GPIO_AFRL_AFRL2_0  | GPIO_AFRL_AFRL3_2 | GPIO_AFRL_AFRL3_1 | GPIO_AFRL_AFRL3_0;
	USART2->CR1 |= USART_CR1_OVER8;
	USART2->BRR = 0x08b;
	USART2->CR1 |= USART_CR1_UE | USART_CR1_TE | USART_CR1_RE;
}

int main(void)
{
	__init_all();

	while(1)
	{
		//USART1->TDR = 0xff;
		GPIOB->BSRR |= GPIO_BSRR_BS_12;
		GPIOB->BSRR |= GPIO_BSRR_BS_13;
		GPIOB->BSRR |= GPIO_BSRR_BS_14;
		GPIOB->BSRR |= GPIO_BSRR_BS_15;
		GPIOA->BSRR |= GPIO_BSRR_BS_8;
		GPIOA->BSRR |= GPIO_BSRR_BS_13;
		GPIOA->BSRR |= GPIO_BSRR_BS_14;
		GPIOA->BSRR |= GPIO_BSRR_BS_15;
		//for(int i=0;i<=100000;i++);
		//GPIOB->BSRR |= GPIO_BSRR_BR_12;
	}
}
